name: Build and Run Container

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Podman
      uses: redhat-actions/podman-login@v1
      with:
        registry: quay.io
        username: ${{ secrets.PODMAN_USERNAME }}
        password: ${{ secrets.PODMAN_PASSWORD }} 

    - name: Build container
      run: podman build -f Containerfile.c10s . -t localhost/c10-hs-runner

    - name: Run container
      env:
        USERNAME: ${{ secrets.PODMAN_USERNAME }}
        PASSWORD: ${{ secrets.PODMAN_PASSWORD }} 
      run: podman run -e USERNAME -e PASSWORD localhost/c10-hs-runner:latest